### PR TITLE
Layout

### LINKED ISSUE #36: layout: sometimes items disappear
especially it seems to be possible to drag a parent into a child and both disappear

### PR DESCRIPTION
**Pull request by sgratzl**
e.g. 
```js
import {horizontalSplit, root, tabbing, verticalSplit, view} from 'phovea_ui/src/layout';

const l = root(verticalSplit(0.5,
  horizontalSplit(0.7,
    view('Left').name('Left'),
    view('Right').name('Right')
  ).name('hor').fixed(),
  tabbing(
    view('A').name('A'),
    view('B').name('B'),
    view('C').name('C')
  ).name('tab')
).name('vert').fixed());

document.body.appendChild(l.node);
```

closes #36 #35 #37

### CODE REVIEW

**Comment by thinkh** [comment]
@sgratzl You had a demo application once. Could you please give me hint where to find this application?

**Comment by sgratzl** [comment]
it was just an internal demo, the essential code is the one mentioned in this pr

**Comment by thinkh** [comment]
When dragging a tab container and dropping it onto itself I get an error in AParentLayoutContainer.ts:30:

93573dcf-82bb-4a81-b6d5-264d6c007017

```
Uncaught RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at TabbingLayoutContainer.AParentLayoutContainer.forEach (http://localhost:8080/app.js?cache-bust=${Date.now()}:23899:24)
    at TabbingLayoutContainer.AParentLayoutContainer.resized (http://localhost:8080/app.js?cache-bust=${Date.now()}:23990:14)
    at http://localhost:8080/app.js?cache-bust=${Date.now()}:23990:46
    at Array.forEach (<anonymous>)
    at TabbingLayoutContainer.AParentLayoutContainer.forEach (http://localhost:8080/app.js?cache-bust=${Date.now()}:23899:24)
    at TabbingLayoutContainer.AParentLayoutContainer.resized (http://localhost:8080/app.js?cache-bust=${Date.now()}:23990:14)
    at http://localhost:8080/app.js?cache-bust=${Date.now()}:23990:46
    at Array.forEach (<anonymous>)
    at TabbingLayoutContainer.AParentLayoutContainer.forEach (http://localhost:8080/app.js?cache-bust=${Date.now()}:23899:24)
```

**Comment by thinkh** [comment]
I have to import the layout style separately. I don't know if this is intended or you forgot to import it into `phovea_ui/src/style.scss`.

My manual import looks like this:
```typescript
import 'phovea_ui/src/_bootstrap';
import 'phovea_ui/src/style.scss';
import 'phovea_ui/src/layout/style.scss';
import './style.scss'; // from my demo app
```

**Comment by thinkh** [comment]
In case of a vertical splitter the tooltip for the little arrows is wrong:

grafik

Correct would be `Squeeze Top` and `Sqeeze Bottom`.

**Comment by sgratzl** [comment]
> I have to import the layout style separately. I don't know if this is intended or you forgot to import it into phovea_ui/src/style.scss.

it is part of https://github.com/phovea/phovea_ui/blob/layout/src/layout/index.ts -> I don't know how you imported the layout

**Comment by thinkh** [comment]
> it is part of https://github.com/phovea/phovea_ui/blob/layout/src/layout/index.ts -> I don't know how you imported the layout

You are right. What I missed is not the import for the SCSS files, but the correct height and width of the container. Adding this snippet to the app SCSS it works even without importing the layout SCSS.

```
#app,
#app > .phovea-layout {
  height: 100vh;
  width: 100vw;
}
```

Note: I only have the layout in my #app element.

**Comment by thinkh** [comment]
I created two views: PersistView and RestoreView ([see gist](https://gist.github.com/thinkh/b00e58350b9d3576aa63f8de00e883c7)). The first one creates a JSON dump of the current layout confiugration and the second one takes a JSON string and recoveres the layout.

**Bug when restoring a tabbing view**

Reproduce:
 * Click Persist button and copy the JSON dump
 * Switch to Restore and past the JSON dump
 * Click Restore Layout button 

Example JSON dump
```json
{"type":"root","name":"","fixed":true,"children":[{"type":"split","name":"vert","fixed":true,"children":[{"type":"split","name":"hor","fixed":true,"children":[{"type":"view","name":"Left","fixed":false,"html":"Left"},{"type":"view","name":"Right","fixed":false,"html":"Right"}],"orientation":"HORIZONTAL","ratios":[0.7692307692307692,0.23076923076923078],"fixedLayout":false},{"type":"tabbing","name":"Layout","fixed":false,"children":[{"type":"view","name":"Persist","fixed":false,"view":123},{"type":"view","name":"Restore","fixed":false,"view":234}],"active":0}],"orientation":"VERTICAL","ratios":[0.6666666666666666,0.3333333333333333],"fixedLayout":false}]}
```

Error: A layout is restored, but without the tabbing view. Instead I get another horizontal splitter with left and right...

22e9e242-1e41-44d3-90bb-459e8af8691b


**Other questions**
 * When is `resized()` called? For me it logs 3x at the startup, but then never again. I tried to move the splitter or resize the browser window. I don't get more than 3 resize console logs.
 * How do I get the new size of my view within the `resized()` function?
 * Where do I get a uid for `dumpReference()`?

**Comment by sgratzl** [comment]
> When dragging a tab container and dropping it onto itself I get an error in AParentLayoutContainer.ts:30:

fixed



> Error: A layout is restored, but without the tabbing view. Instead I get another horizontal splitter with left and right...

fixed (btw. nice example)

> When is resized() called? For me it logs 3x at the startup, but then never again. I tried to move the splitter or resize the browser window. I don't get more than 3 resize console logs.

it should be called when e.g. the split ratio changes and you are child of it, when you add the view to another container (e.g. by drag and dropping). The browser window is not observed since I can't know for sure whether it affects the layout. 

> How do I get the new size of my view within the resized() function?

the `resized` method is just a notification that the view has been resized. You can use regular techniques such as `this.node.offsetWidth` to get the size. However, the layouting might not be done, yet. 

> Where do I get a uid for dumpReference()?

depends on your implementation, there is no general solution. In the end the layouting doesn't care. It gets the id using `dumpReference` and uses the view factory during restore to restore the view with the returned id. Everything else is up to the implementation.

**Pull request merged**
